### PR TITLE
add anynines to the picklist

### PR DESCRIPTION
**Pull request by gogolok**
paas.anynines.com

### CODE REVIEW

**Comment by osis** [comment]
@gogolok Thanks for the Pull Request! The other vendors on the list have provided a sponsored account for continuous integration tests. Do you know who I can reach out to for something similar with anynines?

**Comment by gogolok** [comment]
@Osis Sure, contact Patrick Ross pross@avarteq.de and Oliver Wolf owolf@avarteq.de.
I think they will be very glad to help you. Or you just register and tell me your account via rgogolok@avarteq.de

**Comment by osis** [comment]
@gogolok mind doing a quick rebase so I can pull this in?

**Comment by gogolok** [comment]
thanks 👍

**Comment by osis** [comment]
No problem!

**Pull request merged**
